### ISSUE TITLE
Data_process issue

### ISSUE THREAD

**Issue by nwulq** [less-and-less-bugs/HKEmodel#1]
您好，非常感谢你所做的工作，目前正在复现。在data_process预处理数据时，有一个疑惑。在Visualization for twitter-image pair，有一个img_switch = Image.open("./sarcasm/demo.png")的操作，同时，之后还有一个img_1.save('demo_images/' + '8' + '.png')的操作，在提供的sarcasm数据中，未发现demo.png和demo_images，请问下，这两部分如何获取，如果能解答，不胜感激！

**Comment by less-and-less-bugs** [comment]
那是我做论文可视化的时候写的demo， demo.png 是自己选择的图片。

Visualization for twitter-image pair与数据集的预处理没有关系，建议跳过。

论文所使用的数据已经上传到onedrive上，参见Readme.md

**Comment by nwulq** [comment]
> 那是我做论文可视化的时候写的demo， demo.png 是自己选择的图片。
> 
> Visualization for twitter-image pair与数据集的预处理没有关系，建议跳过。
> 
> 论文所使用的数据已经上传到onedrive上，参见Readme.md

非常感谢您，您的工作没有问题，是我的疏忽，在我仔细阅读后解决了此问题。目前已经可以进行knowledge的生成，还有一个疑问想请教下您，关于knowledge部分，数据中用到了的gecaption文件以及anp文件下的json文件，我读了代码未发现关于这部分的相关处理，请问这两个文件下的json文件是如何生成的？期待您的解答

**Comment by less-and-less-bugs** [comment]
论文中有详细的介绍。是通过相关的预训练模型生成的。建议阅读论文
